force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Attendee_Type__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Type__c</fullName>
    <label>Attendee Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>Speaker</fullName>
            </value>
            <value>
                <fullName>Sponsor Representative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Type__c</fullName>
    <label>Ticket Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Admission</fullName>
            </value>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>Early Bird</fullName>
            </value>
            <value>
                <fullName>Group Discount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AttendeeController.cls
public with sharing class AttendeeController {
  /*  @AuraEnabled
    public static string RegisterAndPay(Map<String, String> attendeeMap){
     

      String paymentResponse = callPaymentGateway(ticket);
      if( paymentResponse == 'Success'){
          //update payment status
          ticket.Payment_Status__c = 'Paid';
      }else{
        ticket.Payment_Status__c = 'Failed';
      }
       update ticket;
      return paymentResponse == 'Success' ? 'Payment Successful' : 'Payment Failed';
    }
    @TestVisible
    private static String callPaymentGateway(Ticket__c ticket){
      HttpRequest req = new HttpRequest();
      req.setEndpoint('https://mockpaymentgateway.com/verify');
      req.setMethod('POST');
      req.setBody('ticketId='+ticket.id+'&amount=100');
      HttpResponse res = new HttpResponse();
  
      if(res.getStatusCode() == 200){
        return 'Success';
      }else{
        return 'Failed';
      }
    }*/ 
    
    @AuraEnabled
    public static void createAttendee(String attendeeId, Id eventId, String attendeeName, String attendeeEmail, String attendeeCompany,String attendeeType, String ticketType) {
        Attendee__c attendee;
        
        if (String.isNotBlank(attendeeId)) {
            attendee = [SELECT Id, Name, Email__c,ComPany__c, Attendee_Type__c, Event__c FROM Attendee__c WHERE Id = :attendeeId LIMIT 1];
        } else {

            attendee = new Attendee__c();
        }
        
        attendee.Name = attendeeName;
        attendee.Email__c = attendeeEmail;
        attendee.ComPany__c = attendeeCompany;
        attendee.Attendee_Type__c = attendeeType; 
        attendee.Event__c = eventId;

        
        upsert attendee;
        
        
        Ticket__c ticket = [SELECT Id, Ticket_Type__c, Payment_Status__c, Attendee__c, Event__c FROM Ticket__c WHERE Attendee__c = :attendee.Id AND Event__c = :eventId LIMIT 1];
        
        if (ticket == null) {
            ticket = new Ticket__c();
        }
        
       
        ticket.Ticket_Type__c = ticketType;
        ticket.Payment_Status__c = 'Pending'; 
        ticket.Attendee__c = attendee.Id;
        ticket.Event__c = eventId;
        
        
        upsert ticket;
    }

}
  